export const LOCAL_FIXTURES = {
  tasks: [
    {
      comment_count: 0,
      completed: false,
      content: 'Get milk (local)',
      id: 1,
      label_ids: [1, 7],
      order: 1,
      priority: 2,
      project_id: 1,
      section_id: 1,
      url: 'https://todoist.com/showTask?id=1',
    },
    {
      comment_count: 1,
      completed: false,
      content: 'Plan a thing (local)',
      id: 2,
      label_ids: [1, 6],
      order: 2,
      priority: 3,
      project_id: 2,
      section_id: 0,
      url: 'https://todoist.com/showTask?id=2',
    },
    {
      comment_count: 0,
      completed: false,
      content: 'Buy the thing (local)',
      id: 3,
      label_ids: [2, 8, 10],
      order: 3,
      priority: 1,
      project_id: 3,
      section_id: 0,
      url: 'https://todoist.com/showTask?id=3',
    },
    {
      comment_count: 0,
      completed: false,
      content: 'Sign up for dance class (local)',
      due: { recurring: false, string: '10 okt.', date: '2018-10-10' },
      id: 4,
      label_ids: [3, 6, 9],
      order: 4,
      priority: 1,
      project_id: 4,
      section_id: 0,
      url: 'https://todoist.com/showTask?id=4',
    },
    {
      comment_count: 0,
      completed: false,
      content: 'Project review (local)',
      due: { recurring: false, string: '9 okt.', date: '2018-10-09' },
      id: 5,
      label_ids: [2, 5, 10],
      order: 5,
      priority: 1,
      project_id: 5,
      section_id: 0,
      url: 'https://todoist.com/showTask?id=5',
    },
  ],
  projects: [
    { id: 1, name: 'Inbox (local)', order: 0, indent: 1, comment_count: 0 },
    {
      comment_count: 0,
      id: 2,
      name: 'Next Actions (local)',
      order: 1,
    },
    { id: 3, name: 'Waiting (local)', order: 2, indent: 1, comment_count: 0 },
    {
      comment_count: 0,
      id: 4,
      name: 'Someday/Maybe (local)',
      order: 3,
    },
    { id: 5, name: 'Work (local)', order: 4, indent: 1, comment_count: 0 },
  ],
  labels: [
    { id: 1, name: '15min_local', order: 1 },
    { id: 2, name: '30min_local', order: 2 },
    { id: 3, name: '1hour_local', order: 3 },
    { id: 4, name: '2hours_local', order: 4 },
    { id: 5, name: 'at_work_local', order: 5 },
    { id: 6, name: 'at_home_local', order: 6 },
    { id: 7, name: 'on_road_local', order: 7 },
    { id: 8, name: 'at_store_local', order: 8 },
    { id: 9, name: 'waiting_for_local', order: 9 },
    { id: 10, name: 'next_actions_local', order: 10 },
  ],
  sections: [
    {
      id: 1,
      project_id: 1,
      order: 1,
      name: 'To do (local)',
    },
    {
      id: 2,
      project_id: 1,
      order: 2,
      name: 'Doing (local)',
    },
    {
      id: 3,
      project_id: 1,
      order: 3,
      name: 'Done (local)',
    },
  ],
};

export const REMOTE_FIXTURES = {
  tasks: [
    {
      id: 1,
      project_id: 1,
      section_id: 1,
      content: 'Get milk',
      completed: false,
      label_ids: [1, 7],
      order: 1,
      priority: 2,
      comment_count: 0,
      url: 'https://todoist.com/showTask?id=1',
    },
    {
      id: 2,
      project_id: 2,
      section_id: 0,
      content: 'Plan a thing',
      completed: false,
      label_ids: [1, 6],
      order: 2,
      priority: 3,
      comment_count: 1,
      url: 'https://todoist.com/showTask?id=2',
    },
    {
      id: 3,
      project_id: 3,
      section_id: 0,
      content: 'Buy the thing',
      completed: false,
      label_ids: [2, 8, 10],
      order: 3,
      priority: 1,
      comment_count: 0,
      url: 'https://todoist.com/showTask?id=3',
    },
    {
      id: 4,
      project_id: 4,
      section_id: 0,
      content: 'Sign up for dance class',
      completed: false,
      label_ids: [3, 6, 9],
      order: 4,
      priority: 1,
      comment_count: 0,
      due: { recurring: false, string: '10 okt.', date: '2018-10-10' },
      url: 'https://todoist.com/showTask?id=4',
    },
    {
      id: 5,
      project_id: 5,
      section_id: 0,
      content: 'Project review',
      completed: false,
      label_ids: [2, 5, 10],
      order: 5,
      priority: 1,
      comment_count: 0,
      due: { recurring: false, string: '9 okt.', date: '2018-10-09' },
      url: 'https://todoist.com/showTask?id=5',
    },
  ],
  projects: [
    { id: 1, name: 'Inbox', order: 0, indent: 1, comment_count: 0 },
    { id: 2, name: 'Next Actions', order: 1, indent: 1, comment_count: 0 },
    { id: 3, name: 'Waiting', order: 2, indent: 1, comment_count: 0 },
    { id: 4, name: 'Someday/Maybe', order: 3, indent: 1, comment_count: 0 },
    { id: 5, name: 'Work', order: 4, indent: 1, comment_count: 0 },
  ],
  labels: [
    { id: 1, name: '15min', order: 1 },
    { id: 2, name: '30min', order: 2 },
    { id: 3, name: '1hour', order: 3 },
    { id: 4, name: '2hours', order: 4 },
    { id: 5, name: 'at_work', order: 5 },
    { id: 6, name: 'at_home', order: 6 },
    { id: 7, name: 'on_road', order: 7 },
    { id: 8, name: 'at_store', order: 8 },
    { id: 9, name: 'waiting_for', order: 9 },
    { id: 10, name: 'next_actions', order: 10 },
  ],
  sections: [
    {
      id: 1,
      project_id: 1,
      order: 1,
      name: 'To do',
    },
    {
      id: 2,
      project_id: 1,
      order: 2,
      name: 'Doing',
    },
    {
      id: 3,
      project_id: 1,
      order: 3,
      name: 'Done',
    },
  ],
  releases: [
    {
      url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/releases/23502796',
      assets_url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/releases/23502796/assets',
      upload_url:
        'https://uploads.github.com/repos/moranje/alfred-workflow-todoist/releases/23502796/assets{?name,label}',
      html_url:
        'https://github.com/moranje/alfred-workflow-todoist/releases/tag/v100.0.0-alpha.1',
      id: 23502796,
      node_id: 'MDc6UmVsZWFzZTIzNTAyNzk2',
      tag_name: 'v100.0.0-alpha.1',
      target_commitish: 'master',
      name: 'v100.0.0-alpha.1',
      draft: false,
      author: {
        login: 'moranje',
        id: 666528,
        node_id: 'MDQ6VXNlcjY2NjUyOA==',
        avatar_url: 'https://avatars0.githubusercontent.com/u/666528?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moranje',
        html_url: 'https://github.com/moranje',
        followers_url: 'https://api.github.com/users/moranje/followers',
        following_url:
          'https://api.github.com/users/moranje/following{/other_user}',
        gists_url: 'https://api.github.com/users/moranje/gists{/gist_id}',
        starred_url:
          'https://api.github.com/users/moranje/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moranje/subscriptions',
        organizations_url: 'https://api.github.com/users/moranje/orgs',
        repos_url: 'https://api.github.com/users/moranje/repos',
        events_url: 'https://api.github.com/users/moranje/events{/privacy}',
        received_events_url:
          'https://api.github.com/users/moranje/received_events',
        type: 'User',
        site_admin: false,
      },
      prerelease: true,
      created_at: '2020-02-08T11:18:19Z',
      published_at: '2020-02-08T11:18:35Z',
      assets: [
        {
          url:
            'https://api.github.com/repos/moranje/alfred-workflow-todoist/releases/assets/17888796',
          id: 17888796,
          node_id: 'MDEyOlJlbGVhc2VBc3NldDE3ODg4Nzk2',
          name: 'Alfred.Workflow.Todoist.alfredworkflow',
          label: 'Alfred Workflow Todoist.alfredworkflow',
          uploader: {
            login: 'moranje',
            id: 666528,
            node_id: 'MDQ6VXNlcjY2NjUyOA==',
            avatar_url: 'https://avatars0.githubusercontent.com/u/666528?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/moranje',
            html_url: 'https://github.com/moranje',
            followers_url: 'https://api.github.com/users/moranje/followers',
            following_url:
              'https://api.github.com/users/moranje/following{/other_user}',
            gists_url: 'https://api.github.com/users/moranje/gists{/gist_id}',
            starred_url:
              'https://api.github.com/users/moranje/starred{/owner}{/repo}',
            subscriptions_url:
              'https://api.github.com/users/moranje/subscriptions',
            organizations_url: 'https://api.github.com/users/moranje/orgs',
            repos_url: 'https://api.github.com/users/moranje/repos',
            events_url: 'https://api.github.com/users/moranje/events{/privacy}',
            received_events_url:
              'https://api.github.com/users/moranje/received_events',
            type: 'User',
            site_admin: false,
          },
          content_type: 'text/plain',
          state: 'uploaded',
          size: 1378680,
          download_count: 2,
          created_at: '2020-02-08T11:18:32Z',
          updated_at: '2020-02-08T11:18:33Z',
          browser_download_url:
            'https://github.com/moranje/alfred-workflow-todoist/releases/download/v100.0.0-alpha.1/Alfred.Workflow.Todoist.alfredworkflow',
        },
      ],
      tarball_url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/tarball/v100.0.0-alpha.1',
      zipball_url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/zipball/v100.0.0-alpha.1',
      body:
        '# [100.0.0-alpha.1](https://github.com/moranje/alfred-workflow-todoist/compare/v99.8.4...v100.0.0-alpha.1) (2020-02-08)\n\n\n### Features\n\n* **project:** full rewrite ([2849c8a](https://github.com/moranje/alfred-workflow-todoist/commit/2849c8a081f4254610ac41125c79fed9a55e557d)), closes [#128](https://github.com/moranje/alfred-workflow-todoist/issues/128) [#126](https://github.com/moranje/alfred-workflow-todoist/issues/126) [#20](https://github.com/moranje/alfred-workflow-todoist/issues/20) [#124](https://github.com/moranje/alfred-workflow-todoist/issues/124) [#128](https://github.com/moranje/alfred-workflow-todoist/issues/128) [#126](https://github.com/moranje/alfred-workflow-todoist/issues/126) [#124](https://github.com/moranje/alfred-workflow-todoist/issues/124) [#20](https://github.com/moranje/alfred-workflow-todoist/issues/20)\n* **project:** provide a useful error as a list item when node.js is not installed ([e039157](https://github.com/moranje/alfred-workflow-todoist/commit/e0391577db34aa353fd1458698e7304a51821303))\n\n\n### BREAKING CHANGES\n\n* **project:** Improve string parsing, now requires id for project, labels and sections\n\n\n\n',
    },
    {
      url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/releases/22240689',
      assets_url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/releases/22240689/assets',
      upload_url:
        'https://uploads.github.com/repos/moranje/alfred-workflow-todoist/releases/22240689/assets{?name,label}',
      html_url:
        'https://github.com/moranje/alfred-workflow-todoist/releases/tag/v99.8.4',
      id: 22240689,
      node_id: 'MDc6UmVsZWFzZTIyMjQwNjg5',
      tag_name: 'v99.8.4',
      target_commitish: 'master',
      name: 'v99.8.4',
      draft: false,
      author: {
        login: 'moranje',
        id: 666528,
        node_id: 'MDQ6VXNlcjY2NjUyOA==',
        avatar_url: 'https://avatars0.githubusercontent.com/u/666528?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/moranje',
        html_url: 'https://github.com/moranje',
        followers_url: 'https://api.github.com/users/moranje/followers',
        following_url:
          'https://api.github.com/users/moranje/following{/other_user}',
        gists_url: 'https://api.github.com/users/moranje/gists{/gist_id}',
        starred_url:
          'https://api.github.com/users/moranje/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/moranje/subscriptions',
        organizations_url: 'https://api.github.com/users/moranje/orgs',
        repos_url: 'https://api.github.com/users/moranje/repos',
        events_url: 'https://api.github.com/users/moranje/events{/privacy}',
        received_events_url:
          'https://api.github.com/users/moranje/received_events',
        type: 'User',
        site_admin: false,
      },
      prerelease: false,
      created_at: '2019-12-15T20:54:20Z',
      published_at: '2019-12-15T20:54:32Z',
      assets: [
        {
          url:
            'https://api.github.com/repos/moranje/alfred-workflow-todoist/releases/assets/16813046',
          id: 16813046,
          node_id: 'MDEyOlJlbGVhc2VBc3NldDE2ODEzMDQ2',
          name: 'Alfred.Workflow.Todoist.alfredworkflow',
          label: 'Alfred Workflow Todoist.alfredworkflow',
          uploader: {
            login: 'moranje',
            id: 666528,
            node_id: 'MDQ6VXNlcjY2NjUyOA==',
            avatar_url: 'https://avatars0.githubusercontent.com/u/666528?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/moranje',
            html_url: 'https://github.com/moranje',
            followers_url: 'https://api.github.com/users/moranje/followers',
            following_url:
              'https://api.github.com/users/moranje/following{/other_user}',
            gists_url: 'https://api.github.com/users/moranje/gists{/gist_id}',
            starred_url:
              'https://api.github.com/users/moranje/starred{/owner}{/repo}',
            subscriptions_url:
              'https://api.github.com/users/moranje/subscriptions',
            organizations_url: 'https://api.github.com/users/moranje/orgs',
            repos_url: 'https://api.github.com/users/moranje/repos',
            events_url: 'https://api.github.com/users/moranje/events{/privacy}',
            received_events_url:
              'https://api.github.com/users/moranje/received_events',
            type: 'User',
            site_admin: false,
          },
          content_type: 'text/plain',
          state: 'uploaded',
          size: 1160421,
          download_count: 354,
          created_at: '2019-12-15T20:54:29Z',
          updated_at: '2019-12-15T20:54:29Z',
          browser_download_url:
            'https://github.com/moranje/alfred-workflow-todoist/releases/download/v99.8.4/Alfred.Workflow.Todoist.alfredworkflow',
        },
      ],
      tarball_url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/tarball/v99.8.4',
      zipball_url:
        'https://api.github.com/repos/moranje/alfred-workflow-todoist/zipball/v99.8.4',
      body:
        '## [99.8.4](https://github.com/moranje/alfred-workflow-todoist/compare/v5.8.3...v99.8.4) (2019-12-15)\n\n\n### Bug Fixes\n\n* **alfred:** notifications not showing in Alfred v4 ([93c7307](https://github.com/moranje/alfred-workflow-todoist/commit/93c7307137983647183171b07ba2a04008b18407)), closes [#125](https://github.com/moranje/alfred-workflow-todoist/issues/125)\n* **dependency:** lower required node.js to v10.x ([a222d5d](https://github.com/moranje/alfred-workflow-todoist/commit/a222d5d50d4c1d3b943b13b7332eedf6f403ace6))\n* **settings:** no update notifications for alfa and beta releases ([1ad3186](https://github.com/moranje/alfred-workflow-todoist/commit/1ad31860379f108025f51c5a1bbcfe8ed5a4d868))\n\n\n\n',
    },
  ],
};
